name: Swift

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:

    runs-on: macos-latest

    steps:
    - uses: actions/checkout@v2
    - name: Build
      run: swift build -v
    - name: Run tests
      run: swift test -v
    - name: Check linux main
      run: swift test --generate-linuxmain && git diff --exit-code Tests
    - name: Check docs
      run: |
        brew reinstall graphviz # Needed for generating the dependency graph
        make docs && git diff --exit-code docs
